### PR TITLE
Enhancement: Add Composer script for simplifying running tests locally

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a composer script to simplify running tests locally

:information_desk_person: This would come in handy, too, if we want to start using `php-cs-fixer`!

Run

```
$ composer test
```

to run all the things.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I agree that a build system could be helpful, but `make` seems not very idiomatic with respect to what I have seen in the PHP world. Alternatives, for example from the Symfony community?

**Comment by localheinz** [comment]
@giorgiosironi 

Not sure, some people use https://www.phing.info!

**Comment by giorgiosironi** [comment]
I have used Phing for a while, seems stable but old-school. Let me take a look around...

**Comment by localheinz** [comment]
@giorgiosironi 

:+1:

**Comment by localheinz** [comment]
I have used it before, too, can amend the PR if you prefer to use it instead.

**Comment by giorgiosironi** [comment]
PHPUnit uses Phing, there is also the low-profile Composer `scripts` key:
https://github.com/Seldaek/monolog/blob/master/composer.json#L58

**Comment by giorgiosironi** [comment]
Things such as Robo are overengineered for a PHP library instead.

**Comment by localheinz** [comment]
@giorgiosironi 

The advantage of using Phing is that one can specify dependencies, right? Which would you prefer?

**Comment by giorgiosironi** [comment]
I'd say go with composer scripts for now, and only switch to Phing in the future if really needed or when we discover a standard tool.

**Comment by localheinz** [comment]
@giorgiosironi 

:+1:

**Pull request merged**
