### PR TITLE
rand() abstraction

### PR DESCRIPTION
**Pull request by giorgiosironi**
We need to be able to configure the random number generator, for the user to be able to tweak performance, adherence to the uniform distribution and server support:
- `rand` native function
- `mt_rand` from the `math` extension
- ~~the `ircmaxell/random-lib` library~~ potential new libraries

In order to do that `Generator` instances must be able to access a `$rand` service represented as an object or a callable. Injecting it in the constructor is not possible as the `Generator\int()` and similar functions are creating the instances with an hardcoded call, so the only solution I could think of was to pass it as a parameter to `__invoke()`.
Also, the `Size` class has been extracted to isolate and test the generation of sizes.

Examples show functionality which is also tested by `Eris\ExampleEnd2EndTest`:
- `AlwaysFailsTest` is run one, run again with the printed seed, and generated the same failure message
- `RandConfigurationTest` shows how to force usage of `rand` or `mt_rand`, we will change the default later.
- `SizeTest` increases the size. Here there was a bug where size would never get to more than `990` with 100 iterations, as the generated size list was `[0, ..., 990, ...]` where 990 is the 100-th element.

Shrinking is still random and not isolated into the new interface, but we can do better than just extract the `rand()` calls. That's a story for another time...

### CODE REVIEW

**Comment by razielgn** [comment]
Looks good. :+1:

**Comment by MirkoBonadei** [comment]
:+1: Good also for me.
This will also enable us to think about splittable RNGs.

**Comment by giorgiosironi** [comment]
Added a pure PHP random number generator, for cases where `rand()` and `mt_rand()` mess with the process global state (e.g. the production code is calling them.)

**Comment by giorgiosironi** [comment]
HHVM apparently segfaults. Likely solution to only provide this Generator on PHP implementations.

**Comment by giorgiosironi** [comment]
Now green, skipping HHVM support.

**Pull request merged**
