### PR TITLE
WIP: Allow PHPUnit 5.x

### PR DESCRIPTION
**Pull request by davedevelopment**
WIP because I'm not sure if we want to add to the travis script. I think PHPUnit 5.x requires PHP 5.6, so both versions will get exercised, but we might want to be explicit about running both at some point

### CODE REVIEW

**Comment by davedevelopment** [comment]
Oh, given the lock file is committed, I guess the travis config will need some changes. Will be back with those.

**Comment by giorgiosironi** [comment]
We were planning on removing the composer.lock as I learned it's a bad practice to keep it on libraries.
I agree it is important to continue to test with both PHPUnit 4.x and 5.x.

**Comment by davedevelopment** [comment]
Removed the lock file, so as it stands, the travis build runs PHPUnit 5.x for PHP 5.6 and HHVM, PHPUnit 4.x for PHP <5.6.

**Comment by giorgiosironi** [comment]
I've put the composer.lock into .gitignore.
Thanks!

**Pull request merged**
